### ISSUE TITLE
Clarifications on specific formula implementations in IR spectra calculation

### ISSUE THREAD

**Issue by DavidCdeB** [efremdan1/calc-ir-spectra-from-lammps#1]
I trust this message reaches you in good spirits and health. First and foremost, I would like to extend my gratitude for the script that you have shared; it has proven to be immensely beneficial.

I am reaching out to seek clarifications regarding the calculations of `autocorr`, `spectra`, among others, in your code. I have invested a significant amount of time in understanding the relevant equations from the literature, and there are some aspects of the implementation that I find somewhat intricate.

The equations pertinent to this problem are eloquently and comprehensively described in Ref [1]. For instance, the IR absorption coefficient $\alpha (\omega)$  is assumed to be calculated as:

$$\alpha (\omega) = \frac{ \omega}{3 \hbar c V n(\omega)} (1- e^{-\beta \hbar \omega })  I(\omega)$$

Where $I(\omega)$ is

$$I(\omega) =  \int_{-\infty}^{\infty} \text{d}t  \quad  e^{-i \omega t} \left \langle \boldsymbol{\mu} (0) \cdot \boldsymbol{\mu} (t) \right \rangle$$ 

- Is `autocorr` =  $\left \langle \boldsymbol{\mu} (0) \cdot \boldsymbol{\mu} (t) \right \rangle$ ?
- Is `lineshape` = $I(\omega)$?
- Where is the refractive index, $n(\omega)$, accounted for in the implementation?
- How is the volume, $V$, included in the implementation?
- What about the $3 \hbar c$ factor?

[1] https://pubs.acs.org/doi/pdf/10.1021/jp034788u

**Comment by EfremBraun** [comment]
> * Is `autocorr` =  ⟨μ(0)⋅μ(t)⟩ ?
> * Is `lineshape` = I(ω)?
Yes and yes.
> * Where is the refractive index, n(ω), accounted for in the implementation?
It is assumed to be constant over the wavelengths considered. See the references mentioned in the README for information on when this assumption this is applicable.
> * How is the volume, V, included in the implementation?
> * What about the 3ℏc factor?
The volume and 3ℏc factor are constants that don't affect the lineshape. It's simply a scale on the y-axis of the spectral graph.
